### ISSUE TITLE
Node is not optional

### ISSUE THREAD

**Issue by Godzil** [r3c/yaronet#1]
Cf the INSTALL.md:

>Node.js v10.13.0 or above (you can skip this dependency but won't be able to deploy to production)
>   imagemin, imagemin-cli, less, less-plugin-clean-css & uglify-js packages

As node.js is needed to build the deval library, it can't be considered as optional (unless there are prebuild version of that library)
Also the "manual installation" documentation does not say anything about having to build the deval library and/or use a pre-generated version.

**Comment by Godzil** [comment]
Ok so the [release 1.0](https://github.com/r3c/deval/releases/download/1.0.0/deval-1.0.0.zip) of deval seems in have the parser.php file, but not the [release 1.1](https://github.com/r3c/deval/releases/download/1.1.0/deval-1.1.0.zip) :sweat_smile:

**Comment by r3c** [comment]
I just pushed a new Deval release with missing `parser.php` file and updated documentation in d5d1398, should be OK now.
