### ISSUE TITLE
Vulnerability in clean-css  (dependency of less-plugin-clean-css)

### ISSUE THREAD

**Issue by cervoise** [r3c/yaronet#4]
When check the project with npm audit, a low vulnerability is reported:

```
$ /usr/local/bin/npm audit
                                                                                
                       === npm audit security report ===                        
                                                                                
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ clean-css                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.1.11                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ less-plugin-clean-css                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ less-plugin-clean-css > clean-css                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/785                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 1 low severity vulnerability in 19 scanned packages
  1 vulnerability requires manual review. See the full report for details.

```

The plugin shall be updated.

**Comment by r3c** [comment]
Hello, thank you for reporting. Unfortunately it seems I'm already using the latest version of less-plugin-clean-css, which is affected by the vulnerability. Let me know if you have a suggestion about how to fix this, however from the description this vulnerability can only be triggered with malicious CSS code being added to this repo and would affect build only, so the threat seems really low here.

**Comment by cervoise** [comment]
Hi,

The developper patched the depedency on Github (https://github.com/less/less-plugin-clean-css/) but not on NPMJS.org. However, this issue (https://github.com/less/less-plugin-clean-css/issues/29) shows that a fork was done in order to solve the issue by using this package https://www.npmjs.com/package/@wikimedia/less-plugin-clean-css.

Indeed, the risk is low, however an admin could try to add/edit some CSS and may trigger this vulnerability. I do not know if a privileged user can edit some CSS somewhere (I haven't try the soft as a privileged user, I'm still trying to solve the docker issue).

**Comment by r3c** [comment]
Unless there is another security issue I'm not aware of, CSS can't be modified without changing and deploying the source code, so I don't think it open any new door for an attack.
