### ISSUE TITLE
Docker up not working

### ISSUE THREAD

**Issue by cervoise** [r3c/yaronet#5]
Docker up is not working, first issue is:

```
web_1  | setup/configure.sh: 50: setup/configure.sh: rsync: not found
```

It can be fixed by adding rsync in yaronet/setup/docker/Dockerfile. (I can do a PR for that).

```
RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
        libmcrypt-dev \
        gnupg \
        locales \
        rsync \
```

Then another bug exist, the connection to the databases is not working:

```
web_1  | Warning: mysqli::__construct(): (HY000/1130): Host '172.18.0.3' is not allowed to connect to this MySQL server in /opt/yaronet/setup/docker/initdb.php on line 12
web_1  | 
web_1  | MySQL Connection Error: (1130) Host '172.18.0.3' is not allowed to connect to this MySQL server
web_1  | Retrying...(9)
```

I did not investigate this one.

Note: docker up reports a low vulnerability on a NPM package, see https://github.com/r3c/yaronet/issues/4.

**Comment by r3c** [comment]
Hi! Thank you for reporting this issue :) As Docker configuration is an external contribution which I'm not using, I won't be able to fix it myself. Feel free to send a PR!

**Comment by UtherII** [comment]
I had the same issue and I just issued a pull request.
